apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: memory-nodes
    labels:
        role: memory
spec:
    selector:
        matchLabels:
            role: memory
    template:
        metadata:
            labels:
                role: memory
        spec:
            nodeSelector:
                role: memory
            hostNetwork: true
            containers:
                - name: memory-container
                  image: admwyx/dinomo:asymnvm
                  imagePullPolicy: Always
                  securityContext:
                      privileged: true
                  env:
                      - name: SERVER_TYPE
                        value: "memory"
                      - name: ROUTING_IPS
                        value: ROUTING_IPS_DUMMY
                      - name: MGMT_IP
                        value: MGMT_IP_DUMMY
                      - name: SEED_IP
                        value: SEED_IP_DUMMY
                      - name: MON_IPS
                        value: MON_IPS_DUMMY
                      - name: REPO_ORG
                        value: admwyx
                      - name: REPO_BRANCH
                        value: master
            imagePullSecrets:
                - name: regcred
