apiVersion: v1
kind: Pod
metadata:
    name: management-pod
    labels:
        role: management
spec:
    restartPolicy: Never
    containers:
        - name: management-container
          image: admwyx/dinomo:management
          imagePullPolicy: Always
          env:
              - name: DINOMO_CLUSTER_NAME
                value: CLUSTER_NAME
              - name: REPO_ORG
                value: admwyx
              - name: REPO_BRANCH
                value: master
              - name: ANNA_REPO_ORG
                value: admwyx
              - name: ANNA_REPO_BRANCH
                value: master
    imagePullSecrets:
        - name: regcred
    nodeSelector:
        role: general
